module.exports.PIN_DOCUMENT = 'PIN_DOCUMENT';
module.exports.DELETE_DOCUMENT = 'DELETE_DOCUMENT';
module.exports.UNPIN_DOCUMENT = 'UNPIN_DOCUMENT';
module.exports.RECEIVED_DOCUMENTS = 'RECEIVED_DOCUMENTS';